Initial Swing-GUI
FunThomas424242/DupFinder-GUI pull request #3
Opened 2017-01-26 22:52 UTC by mkymikky

This GUI is transferred from the CLI Library DupFinder

Signed-off-by: Claus Wollnik <c.wollnik@web.de>

2017-01-26 23:00 UTC, mkymikky commented
DupFinder muss als Artefakt zur Verfügung stehen, damit dieses Projekt läuft.

2017-01-28 09:18 UTC, FunThomas424242 commented
Vielen Dank für den Pull Request.
Nachdem ich mir den Build angeschaut habe ist mir auch wieder eingefallen das wir vorher noch unbedingt die binaries vom DupFinder Project auf bintray releasen sollten da die gui diese ja als Dependency anziehen möchte :)
Bis dahin lässt es sich halt nur lokal bauen. Ich schau mir den Request heute mal kurz an. Weiß aber noch nicht wieviel Zeit ich aktuell reinstecken kann, bin die nächsten Tage auf Schulung.

2017-01-28 15:35 UTC, FunThomas424242 commented
Lol - das ist ja wirklich nur alles rausgezogen :)
Also bevor ich es in den master merge sollten da noch ein paar Dinge geändert werden - kann ich auch machen - wird aber vermutlich erst nächstes WE.  Solange merge ich ihn in einen separaten Branch: **pullrequest/#3**
1. Die Klasse DupFinder muss raus - die wird importiert aus der Abhängigkeit zum DupFinder.
2. Das ganze gestarte muss in in der GUI Klasse passieren, die muss dann auch eine Instanz vom DupFinder hochziehen. 
3. Die Package Namen muss ich meiner Konvention anpassen sonst sieht das auf bintray blöd aus.
4. Das Deployment muss angepasst werden. Das MainClass Attribut im Manifest fehlt und dann muss das bintray Deployment rein.

2017-01-28 15:41 UTC, Huluvu424242 requested changes
Lol - das ist ja wirklich nur alles rausgezogen :)
Also bevor ich es in den master merge sollten da noch ein paar Dinge geändert werden - kann ich auch machen - wird aber vermutlich erst nächstes WE.  Solange merge ich ihn in einen separaten Branch: **pullrequest/#3**
1. Die Klasse DupFinder muss raus - die wird importiert aus der Abhängigkeit zum DupFinder.
2. Das ganze gestarte muss in in der GUI Klasse passieren, die muss dann auch eine Instanz vom DupFinder hochziehen. 
3. Die Package Namen muss ich meiner Konvention anpassen sonst sieht das auf bintray blöd aus.
4. Das Deployment muss angepasst werden. Das MainClass Attribut im Manifest fehlt und dann muss das bintray Deployment rein. 

**Uuups** das DupFinder Projekt sieht ja aktuell ganz anders aus - wie kann das denn jetzt als Lib genutzt werden? Ich stelle @mkymikky da mal ein issue mkymikky/DupFinder/#17 ein

2017-02-16 21:15 UTC, merged

2017-02-16 21:24 UTC, FunThomas424242 commented
Thanks - god work :)